# Generated by Django 5.1.7 on 2025-04-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaredasModel',
            new_name='TarefaModel',
        ),
    ]
